name: svg_pan_zoom
version: 0.0.4
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Enables panning and zooming of SVG in an HTML document.
homepage: https://github.com/rwl/svg_pan_zoom
dev_dependencies:
  browser: any
  test: any
