name: svg_pan_zoom
version: 0.0.1
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Enables panning and zooming of SVG in an HTML document.
homepage: https://github.com/rwl/svg_pan_zoom
dev_dependencies:
  unittest: '>=0.11.5+4 <0.12.0'
